### ISSUE TITLE
 L#程序与宿主程序的通信过程中，无法获取到System.Action类型的函数

### ISSUE THREAD

**Issue by meta-42** [lightszero/LSharp#30]
L#程序与宿主程序的通信过程中，无法获取到System.Action类型的函数，报错位置在Context文件的293行。以下是我这边跟踪此问题的一些过程：
   System.Action 无法获取，但 System.Action<object> 这种泛型版本可以获取到。 原因应该是两者不在同一个程序集。  System.Action所在的System.Core.dll    在CLRSharp_Environment的   moduleref，mapType等未看到。

**Comment by lightszero** [comment]
env可以添加搜索符号文件
