### ISSUE TITLE
能否支持MDB？ 

### ISSUE THREAD

**Issue by clayzx** [lightszero/LSharp#9]
在Unity项目使用UnityVS在VS中调试是使用的MDB调试文件，是否能支持这个功能？谢谢！

**Comment by lightszero** [comment]
很遗憾，dll的解析用的是mono.cecil.
pdb的解析用的是mono.cecil.pdb
他们都是开源类库，而且不直接依赖mono.cecil.pdb
很可惜mono.cecil.mdb 这个类库多年没更新，无法解析现在的mdb文件。
所以我们没有好的基础来做这个工作。

**Comment by clayzx** [comment]
你好，谢谢你的回复！

我看到git上Mono.Cecil.Mdb确实有几年没更新了，
但是我看到MonoDevelop里面也有Mono.Cecil.Mdb，
MonoDevelop使用的是Mdb作为调试文件，
能否参考一下MonoDevelop的实现呢？

如果不能用Mdb调试，那Unity中使用L#，使用什么方式调试呢？

**Comment by lightszero** [comment]
pdb很容易获取，你自己copy一份mono.cecil可以试试。mdb支持不需要任何修改。

发自我的 Windows Phone

---

发件人: clayzxmailto:notifications@github.com
发送时间: ‎2015/‎2/‎13 16:28
收件人: lightszero/LSharpmailto:LSharp@noreply.github.com
抄送: lights limailto:lightsever@hotmail.com
主题: Re: [LSharp] 能否支持MDB？  (#9)

你好，谢谢你的回复！

我看到git上Mono.Cecil.Mdb确实有几年没更新了，
但是我看到MonoDevelop里面也有Mono.Cecil.Mdb，
MonoDevelop使用的是Mdb作为调试文件，
能否参考一下MonoDevelop的实现呢？

如果不能用Mdb调试，那Unity中使用L#，使用什么方式调试呢？

---

**Comment by lightszero** [comment]
已经支持mdb了，经过你的提醒，我测试了MonoDevelop中的Mono.Cecil.mdb.这个版本是可以用的。
我已经反编译了这个模块并修改加入了项目中。
你可以参考UnitTest被注释掉的部分
